apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: nginx:1.14.2
    ports:
    - name: "webapp-port"
      containerPort: 80
    startupProbe:
      tcpSocket:
        port: 27018
      periodSeconds: 1
      failureThreshold: 3
      successThreshold: 1
      timeoutSeconds: 1