apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  restartPolicy: Always
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - "/bin/sh"
    - "-c"
    - "echo This is my path: $PATH"