apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-deployment
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  strategy: {}
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - image: vinsdocker/k8s-app:v3
        name: order-service
        env:
        - name: DUMMYT
          value: "8"
        ports:
        - name: "app-port"
          containerPort: 8080