apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deploy
  annotations:
    kubernetes.io/change-cause: "deploying v2"
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - image: vinsdocker/k8s-app:v2
        name: order-service
        ports:
        - name: "app-port"
          containerPort: 80